JGRennison/OpenTTD-patches

- src/lang/german.txt
New translations for improved breakdowns and for adjacent level crossings.
**Attention**: I wasn't able to include the [first commit of adjacent-level-crossings-translation](https://github.com/auge8472/OpenTTD-patches/commit/063c125f20213c03b18f17bf12a297c184555195) into this pull request. I don't know what's wrong.
> Translate de; improved breakdowns, adjacent level crossings

- README.md
I missed Kruemelchen inthe list of translators, because most of the strings was translated to german by Kruemelchen.
> added Kruemelchen to the list of german translators

- src/group_cmd.cpp
Create group from list command does not work properly since create group command has been changed in upstream.
The involved commit is: 3a4b6b476b3de9daa0310280b3866f0eb0d805de
> Fix: Fix "create group from list" command

- jgrpp-changelog.md
The latest release is listed as year 2019, which is incorrect.
> Fix: year of latest release

- src/economy.cpp
I’m still getting the hang of git, so if there’s a better way of doing things, please let me know.
This is the patch to fix issue #154 that I opened earlier today.
> Fix #154: Vehicle will leave station empty if there is a per-cargo "no load" order for the just-unloaded cargo.

- src/command.cpp
- src/script/api/ai/ai_marine.hpp.sq
- src/script/api/game/game_marine.hpp.sq
- src/script/api/script_marine.cpp
- src/script/api/script_marine.hpp
- src/water_cmd.cpp
This feature adds a BuildRiver game script command and loosens the company restriction to allow game scripts to construct rivers as the deity company.
Currently the process of creating maps styled after real-world maps lacks any mechanism to supply a water map (akin to the heightmap) when creating maps. Proper support for this would be nice but involves a few rather large decisions that broadly affect either how heightmaps behave or the UI surrounding importing them. 
The current map generation process involves generating a game script to fill in water using the BuildCanal game script function as there's no BuildRiver. Likewise these canals must be built by a real company. To improve this process the BuildRiver game script command is added so actual rivers can be created (provided the …
> Gamescript river construction

- src/clear_cmd.cpp
- src/company_gui.cpp
- src/lang/english.txt
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings.ini
Pretty simple one here, clear_cmd.cpp is responsible for generating the rocky patches throughout maps. Normally the calculation for how big these patches should be is a flat addition of '5'. In my usual fashion I've turned this into a user controllable setting, 1-255 with the default set to the original hard coded value of 5. 
255 covers a significant portion of the map, which depending on your aesthetic tastes looks ugly as sin; however on a big map with maxheight 127, alpine tree line set at 20 wide with snowline 24, and snow generation controlled by newgrf between 32-127 it looks absolutely gorgeous in OpenGFX landscape (esp. on heightmaps). The big rock patches break up the improved tree generators forests that it covers the entire map with, and provides a real sense of depth to the …
> More rocks landscape options

- src/house.h
- src/saveload/afterload.cpp
- src/saveload/extended_ver_sl.cpp
- src/saveload/extended_ver_sl.h
- src/saveload/saveload_internal.h
- src/saveload/town_sl.cpp
- src/town_map.h
Use an extra unused 5th bit in m3 to boost the max number of house types from 512 to 1024. So-far everything works, construction stages and animations appear unaffected by my hubris.
I'm absolutely certain this has to be more difficult than this but I haven't managed to break it yet even loading several heavyweight .GRF's simultaneously; JPSet Buildings, DPRK Buildings, TTRS, Swedish Houses, NABS and Snow-Aware vanilla TTD buildings.
Out of scope: Changing the max amount of newhouses in a single .grf.
> Extra House ID's

- src/landscape.cpp
- src/lang/english.txt
- src/table/settings.ini
The game now tries to create 10% of the rivers as long and wider rivers and lets the others flow into those.
Also the lake generation can now be deactivated.
If lakes are generated the size is now the set size +- 25% instead of previously anything between 0 and the set size.
> Wider rivers

- src/graph_gui.cpp
- src/lang/english.txt
Prior to this change, the charts were pretty useless. They indicated at most what cargos were speed sensitive and which ones were not.
This change lets the graph show the average transit speed to profit mapping. With this graph it becomes obvious after exactly what speed any further speed increase brings no further profit. This makes train selection way easier.
> Shows payment based on average transit speed

- src/lang/english.txt
- src/misc_gui.cpp
- src/network/network_gui.cpp
- src/terraform_gui.cpp
- src/textbuf_gui.h
Prior to this change, the use of NewObjects often lead to the problem of players trying to clear those and accidentally destroying a rail station or (when using magic bulldozer) an industry. This action cannot be undone.
This change shows a query making sure the player actually wants to destroy the station or industry.
**NOTE: The switch to a std::function no longer allows for the inequality check in ShowQuery in misc_gui. If this was required a different solution has to be found.**
> Query before destroying important structures (rail stations and industries)

- src/network/network_content.cpp
- src/network/network_server.cpp
- src/network/network_udp.cpp
- src/saveload/cargopacket_sl.cpp
- src/saveload/extended_ver_sl.cpp
- src/saveload/saveload.cpp
- src/tunnelbridge_cmd.cpp
Fixing a few type conversion warnings
Crap like "(uint) -1" is why I hate working with C++ code bases... who writes crap like that??
It's a joke that such a thing is even a legal expression. …
> Fix some type conversion warnings

- src/lang/english.txt
- src/lang/german.txt
- src/train.h
- src/train_gui.cpp
When buying a train it is very hard to judge how much a new engine can pull. This can get difficult for new players,
especially when using realistic physics and higher cargo multipliers.
This change displays the weight and max speed both in empty and loaded state. While buying wagons for the train the view updates and the player can check what the current max speed on flat terrain is, when all wagons are fully loaded.
The max speed when loaded is calculated with a fixed rolling friction value based on the maximum speed. This makes sure that if the screen shows that the maximum speed can be reached, this will indeed be possible (this is probably of most interest). However at lower speeds the coefficient is somewhat off so the train might actually be able to go faster since the friction is …
> Show more details on train max speed when loaded

- src/group_gui.cpp
- src/rail_gui.cpp
- src/sortlist_type.h
- src/tracerestrict_gui.cpp
- src/vehicle_gui.cpp
- src/vehicle_gui_base.h
Some NewGRFs adding station tiles overdo it a bit with the category names. Also for some reason the string width returned to the game seems to be too large for some of them. This leads to unnecessarily wide reserved space and makes it awkward to select the actual tiles.
The toggle sort direction button does not actually cause a resort, it just changes the ordering. This means there is no actual button to refresh the sorting. Some of the new sort categories, like timetable delay, change often. So a resort is required.
This sets a maximum width for the left part of the build railstation window. It also makes the toggle sort order button resort the list and adds a button to automatically do so every day. This is convenient when watching the timetable delay and other rapidly changing values. …
> Minor additions

- src/build_vehicle_gui.cpp
- src/lang/english.txt
- src/lang/german.txt
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings.ini
- src/widgets/build_vehicle_widget.h
When buying a train it is advantageous to be able to view, sort, and filter engines and wagons separately. Especially when using large or multiple train sets.
This new train purchase window has two colums. One for locomotives and power cars, one for wagons.
There were multiple changes and updates to the code of the original purchase window since I added this one, so there are a few things not matching up. I fixed and updated what I could see at first glance but there's still a few issues so I'd appreciate some help with this. It's a worthy addition I think when we get it running again. And it shouldn't be hard to do. The code is mainly intact, it's just small API updates and changes from pointers to references or C to C++ types that are the issue.
Some things are not automated, and …
> Advanced train purchase window

- src/cargotype.h
- src/date.cpp
- src/graph_gui.cpp
- src/graph_gui.h
- src/lang/english.txt
- src/saveload/extended_ver_sl.cpp
- src/saveload/extended_ver_sl.h
- src/saveload/station_sl.cpp
- src/station.cpp
- src/station_base.h
- src/station_cmd.cpp
- src/station_gui.cpp
- src/station_type.h
- src/widgets/graph_widget.h
- src/widgets/station_widget.h
- src/window_type.h
It is sometimes hard to tell if the amount of waiting cargo at a station is actually a problem or just a bad looking snapshot of a completely fine situation because the next train will pick up everything. A history of waiting cargo is needed to properly judge the situation.
This adds a cargo history window to each station which shows a graph of the last 48 days of cargo development (updated every 2 days)
@JGRennison Please check the savegame code again. I'm not sure how I do a save with your new system, since we probably don't need to bump the savegame version if we use your feature.
It's also up for you to decide if you want to extend the period that is saved and displayed. Maybe more than 48 days makes sense, like maybe 60 days for 2 full months. Especially if someone plays on a large …
> Add station cargo history

- src/CMakeLists.txt
- src/date.cpp
- src/lang/english.txt
- src/lang/german.txt
- src/misc.cpp
- src/openttd.cpp
- src/saveload/CMakeLists.txt
- src/saveload/afterload.cpp
- src/saveload/extended_ver_sl.cpp
- src/saveload/extended_ver_sl.h
- src/saveload/saveload.cpp
- src/saveload/train_speed_adaptation.cpp
- src/saveload/vehicle_sl.cpp
- src/settings.cpp
- src/settings_gui.cpp
- src/settings_type.h
- src/table/newgrf_debug_data.h
- src/table/settings.ini
- src/train.h
- src/train_cmd.cpp
- src/train_speed_adaptation.h
- src/vehicle.cpp
Without realistic breaking trains would continuously run into the train in front of them.
This change makes them adjust their speed based on trains in front of them.
It breaks when approaching junctions and it does not play nice with the realistic breaking system. The latter smoothes out the effect of the orginal oscillation but it also prevents the ATC from eliminating it because it is more conservative.
A better solution needs to be found to prevent the speed oscillation of trains but this might work as an interim solution when playing without realistic breaking. Since the functionality is all compacted into one single function it can later be easily eliminated once a better solution has been found.
Some things are not automated, and forgotten often. This list is a reminder for the …
> Train speed adaptation

- src/landscape.cpp
- src/lang/english.txt
Additional tweaks to allow rivers to spawn in deserts (causing aditional tropic biome to spawn around them). This piggybacks off of the 'allow lakes in deserts' setting which to be honest never really accomplished what I wanted it to, renaming it to cover both. The actual setting name itself internally hasn't changed in case I break any of the save-game stuff JGR did for me.
In my testing so-far this is is behaving as expected, and along with previous tweaks made earlier it definitely helps rivers that start in rainforest areas actually successfully traverse towards the coast and thus take advantage of the larger rivers patch.
> Allow Rivers in Sub-Tropical climate Deserts

- src/lang/english.txt
- src/roadveh_cmd.cpp
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings/settings.ini
Introduces a new setting (defaulted off) to allow preventing road vehicles from performing so-called quantum tunneling through other vehicles blocking their path. Blame Azusa on discord for the name. I couldn't think of a name for the setting.
It's possible to create amazing traffic jams with this feature. This is intentional. This is officially a 'muh immersion' setting.
Next step is to tweak some road vehicle overtaking behaviors.
> Setting to prevent road vehicles passing through other vehicles when blocked.

- src/main_gui.cpp
When giving money in multiplayer, the amount that can be given is capped at 20 million pounds. When giving amounts larger than this, the network message shows the larger amount even though only 20 million actually gets transferred.
> fix: Give money message showed incorrect value

- src/rail_cmd.cpp
When attempting to remove signals from a bridge or tunnel where either end of the tunnel has a tracerestrict program of any kind, the game crashes with a tile assert. This PR should fix that.
The fix re-orders the state changes to do tracerestrict notifications earlier in the removal change. The assert inside tracerestrict was tripped because it checks that there is an existing signal simulation on the bridge before proceeding. However, in the remove signal command the relevant signal bits had already been cleared, making the tiles appear as if they did not have a signal simulation. The assert then fails.
I don't know well enough what's going on in the signal remove command to know that this order of cleanup works entirely correctly. In testing it seemed fine, but someone more …
> fix: error when removing tunnelbridge signal w/ tracerestrict

- src/station_gui.cpp
The expanded station rating tool tip shows the same value for time since last pickup and cargo waiting.
Show actual time since last pickup.
> Fix: station raiting tooltip showed incorrect time

- src/train_cmd.cpp
When using template replacement with template refit disabled, mirroring the existing train consist can result in the incorrect cargo type being selected in cases where, e.g. the locomotive has a cargo type set for livery or other reasons.
Instead of taking the first valid cargo type, this fix also checks that the vehicle has a non-zero capacity for that cargo. This results in picking a cargo that the existing train being replaced can carry some amount of and should yield successful refits more often.
> Fix: Require non-zero capacity for refit cargo type

- src/screenshot.cpp
Invoking the `screenshot` console command with a filename ending in %d will cause it to be numbered automatically.
As part of running my OpenTTD server I use console scripts to capture a screenshot of the game periodically. I use these screenshots to make time-lapse videos of the game.
However, the default behavior of the console command `screenshot` with a user-provided filename will always save just to that filename, causing it to be overwritten if it exists. The only way to get a 'reel' of screenshots automatically is to omit the filename argument, in which case the screenshots will be saved as e.g. `screenshot.png`, `screenshot#1.png`, `screenshot#2.png`, etc.
The proposed change causes the automatic numbering to happen to any user provided filename that ends in `%d`.
* The `%d` token …
> Change: Automatic screenshot numbering

- src/lang/english.txt
- src/saveload/afterload.cpp
- src/saveload/extended_ver_sl.cpp
- src/saveload/extended_ver_sl.h
- src/settings_gui.cpp
- src/settings_type.h
- src/station_cmd.cpp
- src/table/settings/settings.ini
- src/train.h
- src/train_cmd.cpp
Currently through loading limits the maximum speed of trains to a fixed upper limit of about 9 mph which can significantly impact the load/unload times of long trains. The load/unload time is largely unaffected by platforms that are less than half the length of the train. This leaves little choice for players when designing stations for long trains.
This feature adds a setting to control the maximum allowable through loading speed. This can make platform length more significant in the design of stations as longer platforms now afford trains more space to accelerate between stops. The realistic braking model is likewise respected, meaning short platforms won't afford  trains much opportunity to accelerate. This makes the choice between short platforms and long platforms a bit more engaging …
> Add: Through load speed limit setting

- src/tree_cmd.cpp
Currently the arctic tree range feature only considers the static snow line. With a dynamic snowline from a newGRF the trees look wrong.
**Currently:**
Winter
Summer
**With this change:**
Winter
Summer
The code uses the HighestSnowLine() and LowestSnowLine() functions now, which, if no dynamic snowline is present, will fallback to the previous behavior and both return the static snowline.
None that I can see
* This PR …
> Make arctic treeline feature use the dynamic snowline if present

- src/road_cmd.cpp
Flat road foundations are right now getting the snowy state of the lower z-height. This makes them look visually disconnected from their surroundings.
**Before PR**
**After PR**
Changing the GetTileZ to GetTileMaxZ in the case of flat tiles, including flat foundation tiles, the snow state is always the same as the visually connected tiles.
None
* …
> Fix z-check for flat road foundations

- src/departures_gui.cpp
- src/lang/english.txt
The "Show via" widget gets enabled/disabled as a side effect of "Show departures" being toggled, but it was not being marked dirty for redrawing, leading to some strange behavior.
`LowerWidget` and `RaiseWidget` both simply wrap `SetWidgetLoweredState`, so we can eliminate conditional test and nested call by passing the boolean directly to the latter. Code readability unaffected.
The ordering of strings did not match the ordering of widget enum. Could be fixed by switching the ordering, but instead prefer to ...(see next)
Add dedicated tooltip text for these four widgets, `STR_DEPARTURES_SHOW_*_TOOLTIP`, instead of repurposing `STR_STATION_VIEW_SCHEDULED_*_TOOLTIP` which are for a different window (see `station_gui.cpp`). This lets us change the wording to something more accurate and …
> Various departure boards UI/UX bugfixes/improvements

- src/lang/extra/_checkMissingTranslations.sh
- utils/checkMissingTranslations.sh
- utils/conv-lang.pl
Now that the JGR extra translations are on a different file. I've made a script to get the strings missing on any language file and add them at the end of the file in order to update the translations
It's just a self-explanatory bash script that asks for a language file, in example `galician.txt` and checks each line that is not a comment (beginning with #) on the `english.txt` file. If it founds a missing string (by the string language code), it adds the full line at the end of the language file you are checking, so you can later open it and translate it.
It doesn't replace the codes `STRING1,STRING2,STRING3, RAW_STRING `and so on, so the translator should check them and build the translations to check them.
I've added the bash script inside the extra folder for convenience, but perhaps …
> Add script for updating translations

- src/lang/extra/english.txt
- src/main_gui.cpp
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings/settings.ini
- src/viewport_gui.cpp
If enabled, the setting allows tooltips for tiles, such as industries, to show instantly, when otherwise they would require a right-click.
One of the features in this patchpack is showing tooltips when hovering over tiles on the map. In ancient days it used to be that , if "Show tooltips" setting was set to "Right-click", a right-click would only be required to show a tooltip for an interface widget, while hovering over, for example, an industry would show a tooltip instantly. This was fixed in v0.47.1 release, creating 2 problems:
1. There is a difference between utility of interface and town/industry tooltips for the player. The former provides information that, generally, only changes with updates to the program, while the latter provides real-time gameplay information that may …
> Feature: A setting to bring back old tile tooltip behavior.

- jgrpp-changelog.md
Two typos introduced in the changelog for JGRPP 0.54.3.
Fixed both typos.
None. …
> Fix some typos in jgrpp-changelog.md

- src/lang/extra/english.txt
- src/settings_gui.cpp
- src/settings_type.h
- src/strings.cpp
- src/table/settings/settings.ini
- src/town_cmd.cpp
I was watching [Master Hellish's S10 Let's play](https://www.youtube.com/playlist?list=PLX9TPVcxrORNGh7hpvm0tLwAQNLizP9Qe)
And noticed that City Builder Script had a ".::City::." label on the cities, and thought this would be a handy feature on every game, especially when trying to find Cities quickly (say when comparing two towns with the same resources, and wanting to know what one to invest in at a glance).
Provides a "City in Label" option similar to "Population in Label" option.
I'm `woobilicious` on the discord.
Needs translations.
* This PR touches english.txt or translations? Check the …
> Add an optional "(City)" in Viewport labels

- media/openttd.desktop
Add JGRPP to application name to distinguish openttd+JGRPP from vanilla openttd
If both vanilla openttd and jgrpp are installed in parallel, both launchers have the same name in the applications menu 
change the application name in the desktop file to make Jjgrpp distinguishable from vanilla openttd
none
* ai_changelog.hpp, gs_changelog.hpp need …
> Update openttd.desktop -> add "+JGRPP" to app name

- src/lang/extra/english.txt
A typo introduced in 2bb5c9ac848d5ab3ebbe08ef82880ef406aad205.
Fixed the typo.
None
* ai_changelog.hpp, game_changelog.hpp need updating. …
> Fix 2bb5c9ac84: typo in disable script parameter randomisation helptext

- src/ground_vehicle.cpp
- src/lang/extra/english.txt
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings/game_settings.ini
- src/train.h
This doesn't affect the maximum speed, but does give a much smoother acceleration and deceleration. By default this has no effect, but I have quite liked a value of 25%, particularly in the steam age.
> Add: Acceleration/braking adjustment setting for realistic braking

- src/economy.cpp
- src/lang/extra/english.txt
- src/settings.cpp
- src/settings_gui.cpp
- src/settings_type.h
- src/table/settings/economy_settings.ini
I find that when playing on larger maps, the rate of random industry production changes, such as openings/closings and production rate changes happen entirely far too fast, as these events are scaled by map size. Some newgrf's allow disabling new industries spawning altogether, however I do not desire this, as I still want to allow some industries to spawn however at a greatly reduced rate
This feature changes the calculation used in StartupIndustryDailyChanges in economy.cpp based on conversations had with both JGR and Gwyd on 31/7/2024, first eliminating some clunky old calculations that relied on binary shifts of the total of the log2's of the map edge widths. The new calculation just directly uses the map area for the calculation, multiplied by a percentage which defaults to 100% in …
> Feature: Allow changing the rate of industry events

- src/settings_gui.cpp
The button entry for "bigger main toolbar" in the settings menu is set incorrectly,
misplacing the button.
Fix this problem by rearranging the UI elements.
None that I can think of.
* ai_changelog.hpp, game_changelog.hpp need updating.
* This PR affects the NewGRF API? (label 'needs review: …
> Fix: Incorrect button size for "larger toolbars"

- src/station_gui.cpp
The current station rating tooltip uses four `GfxDrawLine`, which causes problems with larger interface sizes.
|1x|4x|
|---|---|
|![image](https://github.com/user-attachments/assets/74770a83-12a2-4bcb-8cd7-cc0303df5f4c)|![image](https://github.com/user-attachments/assets/bd572f52-e055-4edb-bda2-6b961a975b0e)|
Reference:
https://github.com/citymania-org/cmclient/blob/02d6792570e1ff228d15ba968af9f36e04d23a68/src/citymania/cm_tooltips.cpp#L141-L144
Use this piece of code from cmclient.
There isn't a default gray window fill, so instead of using single rect to overlap the other rect (vanilla tooltips), use four rects.
|1x|2x|4x|
|---|---|---|
|![image](https://github.com/user-attachments/assets/27dd3118-9edc-4a48-9aa2-d7c38dacbfc7)|![image](https://github.com/user-attachments/assets/481aee7e-0 …
> Fix: station rating tooltip outline

- src/lang/extra/english.txt
- src/timetable_gui.cpp
The time bar in the timetable window uses an `hsep_wide` to seperate the arrival/departure abbreviations and the time. This does not work well with languages that use the ideographic colon, or the fullwidth colon, as the gap is now super wide.
|zh_CN (fullwidth colon)|zh_TW (fullwidth colon)|en (halfwidth colon)|
|---|---|---|
|![image](https://github.com/user-attachments/assets/f4227926-3d25-454f-8de8-e0120063bd4b)|![image](https://github.com/user-attachments/assets/e582296e-88eb-44d3-b419-d7d3101568f4)|![image](https://github.com/user-attachments/assets/5a19a6c8-0592-4c45-9a4f-b0f1df61a9cc)|
Remove the `hsep` and add two `{SPACE}` after the abbreviation. It seems like that these strings are only used in the timetables window.
|zh_TW (fullwidth colon)|en (halfwidth colon + 2x `{SPACE}`)| …
> Change: use spaces instead of `hsep` in timetable GUI

- src/programmable_signals_gui.cpp
1. Place a programmable signal.
2. Ctrl+Click it.
3. Insert a "condition".
4. Choose the "slot occupancy" condition type.
5. Choose the "Create a slot" option.
That gives an error message "Can't create counter... That field is not valid for the condition".
Since 42be0b8e0c58c26ba3ff80b0675a3f835aab66e3 query_submode is always QSM_NONE at this point, so the `if (this->query_submode == QSM_NEW_SLOT)` always took the else branch. So, fix the places that read query_submode after it's been overwritten.
The `break;` doesn't make a difference but I threw it in. (I added it locally because I was trying to patch slot creation to also prompt for the new slot's capacity, so I added a switch case for the result of the capacity prompt.)
None that I'm aware of.
Some things are not automated, and …
> Fix slot creation from programmable signals window

- src/vehicle_gui.cpp
The vehicle list should say "profit last period" in wallclock mode, but it actually says "profit last year".
In fact, STR_VEHICLE_LIST_PROFIT_THIS_PERIOD_LAST_PERIOD isn't used anywhere in JGRPP (it is used in OpenTTD, see https://github.com/OpenTTD/OpenTTD/blob/eca826b0a4d0334a1ddcd4237a7c2ef1724d6787/src/vehicle_gui.cpp#L1781).
Use the correct string.
It's weird that the string exists in english.txt, but the C++ files don't use it at all. I'm not sure how this happened.
* This PR …
> vehicle list: Say "period" in wallclock mode

- src/lang/extra/korean.txt
It seems "예약산" is typo, so I want to fix it. CC @telk5093
> Update Korean translate typo

- src/fios.h
- src/fios_gui.cpp
- src/lang/extra/english.txt
- src/lang/extra/galician.txt
- src/lang/extra/korean.txt
- src/lang/extra/simplified_chinese.txt
- src/order_bulk.h
- src/order_cmd.cpp
- src/order_gui.cpp
- src/order_serialisation.cpp
- src/order_serialisation.h
- src/timetable_cmd.cpp
Allows importing serialized order lists without removing all previous orders.
Also has a to be tested implementation for reversing order lists at import.
Probably needs some UI rethinking.
> Add appending serialized order lists

- src/lang/extra/english.txt
- src/saveload/afterload.cpp
- src/settingentry_gui.cpp
- src/settings_type.h
- src/sl/extended_ver_sl.cpp
- src/sl/extended_ver_sl.h
- src/table/settings/game_settings.ini
- src/vehicle.cpp
New setting (expert) under _Disasters / Accidents_ => _Reliability decay factor_, which speeds up or slows down reliability decay 2x, 4x, 16x or 32x
I tested it and the change works in a running game including on non-leading engines in multiheaded trains. It took me some figuring out to get that working (`TrainReliabilityDecayChanged`) and there's probably a neater way to do it.
I don't like that the calculation formula is in two places (`StartupOneEngine` and `TrainReliabilityDecayChanged`) but I'm not sure what better solution there is. Rerunning `StartupOneEngine` in latter function is not an option as that could alter vehicle introduction dates and maximum reliability.
If something (script, newgrf?) modifies `reliability_spd_dec` of a particular vehicle at some point, this setting …
> Add setting for reliability decay speed

- src/zoning_cmd.cpp
I was making a scenario and I wanted to place cities on the 3x3 town road grid. When I tried to view the grid, the zone outlines did not appear.
This MR allows the rest of `DrawTileZone` to be executed when in the scenario editor.
No known limitations.
* ai_changelog.hpp, game_changelog.hpp need updating.
* This PR affects the NewGRF API? (label 'needs review: …
> Change: draw zoning in the scenario editor
