src/lang/korean.txt

Korean Translation

---

src/lang/korean.txt

Add String STR_CONFIG_SETTING_ENABLE_ROAD_CUSTOM_BRIDGE_HEADS and STR_CONFIG_SETTING_ENABLE_ROAD_CUSTOM_BRIDGE_HEADS_HELPTEXT

Translation update for JGRPP 0.17.0

---

src/lang/korean.txt

Not fluently translated and seems that 7 strings are missed.
And it will be great that notice us when you add new strings in next update.

Korean: Update translation

---

src/lang/korean.txt

I added some strings and edited some strings.

Added Korean translations

---

src/lang/korean.txt

Translated STR_CONFIG_SETTING_TOWN_ROAD_OVER_RAIL / STR_CONFIG_SETTING_TOWN_ROAD_OVER_RAIL_HELPTEXT

Add Korean Translations

---

src/lang/german.txt

Translation for
- setting for minimal distance between towns
- setting for towns building street bridges over rails
- setting for random road reconstruction
- setting block map mode

german translation, part 4

---

src/lang/german.txt

- almost complete own translation added (reworked)
- a few corrections to trunk strings
- a few corrections of previous translations

Update German language file

---

src/lang/korean.txt

Please let me aware if there is any problem

ko-KR: Complete translation

---

src/lang/korean.txt

Complete translations + a little improvements

ko-KR: for 0.31.1

---

src/console_cmds.cpp

Fix: Fix some copy-paste typos.

---

src/lang/korean.txt

Update and modify translations for 0.32.0

ko-KR: Update translation

---

src/lang/korean.txt

Thanks for noticing me first, I've done Korean translations for commit 2b0c1a5.

ko-KR: Apply commit 2b0c1a5

---

src/lang/korean.txt

ko-KR: Updates for 0.32.4

---

src/lang/korean.txt

Update korean translation based on 0.33.2

ko-KR: Update for 0.33.2

---

src/lang/japanese.txt

updated japanese translation and more translation

updated japanese translation and more translation

---

jgrpp-changelog.md

0.34.0 was quite an old one! haha XD

Fix year mistake

---

src/lang/korean.txt

ko-KR: Update translations

---

src/lang/korean.txt

Regardless #172, I'll make translation :)

ko-KR: Update translation up to 0.35.0

---

src/lang/korean.txt

This will be more natural for korean users. Thanks for https://github.com/JGRennison/OpenTTD-patches/commit/05dc785f132dafcd5918c89887d5ac5ec099d634

Update: Translations of Korean - Make more natural conditional orders for cargo

---

src/lang/korean.txt

Update: Korean translation update

---

src/lang/korean.txt

Update: Korean translation for v0.38.1

---

src/lang/korean.txt

Update: Korean translation for v0.39.0

---

src/lang/korean.txt

Update: Korean translation for v0.39.1

---

src/vehicle_cmd.cpp

When cloning a vehicle with a sufficiently large integer at the end of its name, the incrementing algorithm would overflow and insert a negative number into the new vehicle name. This was due to an attempt to parse the number into a signed `long` type.
This PR fixes this issue by avoiding parsing the integer altogether and simply incrementing it in-place in the string. Performance should be unaffected as the new algorithm works in place and only needs to reallocate when the number of digits grows. Compared to the previous algorithm which utilized string streams for parsing and formatting, this change may even be an improvement.
Some issues remain unaddressed, such as the requirement that the number be the very last part of the name. Any non-digit characters after a number will cause it to …

Fix: overflow in CloneVehicleName

---

src/lang/korean.txt

Update: Korean translation for v0.39.2

---

src/lang/german.txt

Updates German translation to be on par with version 0.39.2
Playtested

Update: German translation by kruemelmagic

---

src/lang/korean.txt

I haven't experienced this feature though, but this is insane! Nice!

Update: Korean translation for ed0ffb6

---

src/lang/korean.txt

Update: Korean translation for v0.40.2

---

src/video/allegro_v.cpp

Removed from merge commit dfecdf3afb18d131721441813632ee4745c0557f

Fix #220 build fail due to missing var

---

src/lang/korean.txt

Update: Korean translation

---

src/lang/korean.txt

Update: Korean translation for v0.40.4

---

src/lang/korean.txt

Update: Korean translation for v0.40.5

---

README.md
installation.md

Now that this repo has been [added](https://github.com/Homebrew/homebrew-cask/pull/105747) to homebrew, I've added a section in the readme and created installation.md.

Add installation instructions

---

src/lang/korean.txt

Update: Korean translation for v0.41.2 + a

---

src/lang/korean.txt

Update: Korean translation for v0.41.3

---

src/console_cmds.cpp
src/lang/english.txt
src/screenshot.cpp
src/screenshot.h
src/screenshot_gui.cpp
src/widgets/screenshot_widget.h

Adds flat topography and industries screenshot types :)

Add topography and industries screenshot types

---

src/lang/english.txt
src/station_cmd.cpp
src/station_gui.cpp
src/station_gui.h
src/window_type.h

Adds a tooltip explaining how the station rating is calculates.
I also took the liberty to change the age rating check from 1,2,3 years to 10,20,30 years.
It's insane that you only get that full bonus by buying new vehicles every 12 months. Who does that?

Station rating tooltop

---

src/genworld.cpp
src/genworld.h
src/genworld_gui.cpp
src/landscape.cpp
src/lang/english.txt
src/map_func.h
src/pathfinder/npf/aystar.cpp
src/pathfinder/npf/aystar.h
src/pathfinder/npf/npf.cpp
src/road.cpp
src/settings.cpp
src/settings_gui.cpp
src/settings_type.h
src/table/settings.ini
src/terraform_gui.cpp
src/widgets/terraform_widget.h

The map looks empty and unrealistic without a road network. it also makes a gamestart with a simple bus route expensive.
This change adds the generation of a public road network to the map creation process. …

Adds the generation of public roads linking towns together

---

src/fontcache.cpp
src/newgrf_spritegroup.h
src/pathfinder/npf/npf.cpp

Fixes a few of the warnings regarding [Issue #267](https://github.com/JGRennison/OpenTTD-patches/issues/267)

Fix a few compiler warnings

---

src/core/bitmath_func.cpp

FindFirstBit64 had infinite recursion causing a crash or a hang

fix infinite recursion in FindFirstBit64

---

src/lang/galician.txt

I wanted this amazing patch translated in galician, I'm working with a few others to set up a server with a map of Galicia.
It adds missing translations on Galician as well as applying  last changes I've made on the main branch
I have not been able to compile the galician.lng file. I have no errors or warnings:
```
../../build/src/strgen/strgen -w galician.txt
0 warnings and 0 errors for ./galician.lng
```
But file size differs from the one I've downloaded with the patch. 112Kbs(my lng file) Vs 217Kbs(the one from the release v0.44.1). I don't know what can be the caused, as we were discussing on the issue #339

[Feat] Galician Translation

---

src/lang/czech.txt

In Czech translation the shared routing restriction statement made no sense, because it stated "Shared with x signals", while supplied number said result to "How many signals have this shared?", so I changed to "Shared by x signals.
* This PR …

Fix some czech.lng statement to make sense.

---

src/lang/korean.txt

And matches line numbers between english and korean.
Merge this right before next release :)

Update: Korean translation up to 0.45.0

---

src/lang/korean.txt

Nice new features! You are the god of OpenTTD 😁

Update: Korean translation up to 0.46-rc1

---

src/lang/korean.txt

Update: Korean translation up to a7bcb7e

---

src/lang/galician.txt

Hey there! I'm updating Galician translation with the newest translations.
Also for future reference and anyone interested, I've used this bash command to obtain all new translations and add the english version on the bottom of the target language:
From src/lang:
`## ../../build/src/strgen/strgen -w galician.txt 2>&1  | cut -d\' -f 2 | head -n-1 | xargs -I $ grep -w $ english.txt  >> galician.txt`

[Feat] Updated Galician translations up to v0.47.0

---

src/lang/korean.txt

Update: Korean translation up to 2bfa53f

---

src/lang/korean.txt

Merge this right before the new release ;)

Update: Korean translation up to 6107aa9

---

src/lang/korean.txt

I didn't notice that you commented at #390 😅

Update: Korean translation up to v0.47.3

---

src/lang/korean.txt

I couldn't check this translation ingame since I failed to build the game on Windows 😅
Please let me know if there's additional strings :)

Update: Korean translation up to 10b415b

---

src/lang/korean.txt

And match the lines with english's one.
Thanks for awesome feature!

Update: Korean translation up to 0.48.0

---

src/lang/german.txt

Translated most of the missing strings in the German translation. Currently there are 58 untranslated strings left, that I can not translate because of missing knowledge about the affected pathces.

Translated most of the missing strings for German language, stand jgrpp 0.48.0

---

src/lang/korean.txt

Maybe they were mis-translations, so I fixed them.
Please merge this right before new release.
Appreciate always ;)

Update: Korean translation for some route restrict

---

src/lang/german.txt

Make small corrections regarding the orthography in the German lang-file

---

src/lang/korean.txt

Update: Korean translation up to 0.49.0

---

src/lang/galician.txt

Hey there! I'm updating Galician translation with the newest translations.

[Feat] Updated Galician translations up to v0.49.0

---

src/lang/korean.txt

Update: Korean translation up to 0.49.1

---

src/lang/korean.txt

Update: Korean translation up to 0.49.2

---

src/lang/galician.txt

Galician Translations 0.50.0

---

src/lang/korean.txt

Merge this or notify me when next release will be upcoming :)

Update: Korean translation up to e882ba6063

---

src/lang/simplified_chinese.txt

Simplified Chinese localisation update and fix.

Simplified Chinese Translations 0.50.0

---

src/lang/korean.txt

Update: Korean translation up to 312361d

---

src/lang/galician.txt

Checking in from time to time as usual!

Update Galician Language 2023-01-29

---

src/lang/korean.txt

Update: Korean translation up to 85de07d

---

src/lang/extra/korean.txt
src/lang/korean.txt

Note that I modified ``STR_CARGO_TYPE_FILTER_FREIGHT`` in the vanilla WT and updated korean translation up to current commit.

Update: Korean translation according to splitting extra

---

src/lang/extra/korean.txt

Might be updated again since I've never checked where ``STR_ORDER_LABEL_DEPARTURES_VIA_BUTTON`` is used.

Update: Korean translation up to 17e2890

---

src/lang/extra/galician.txt

Hey There! Updating the galician translations! Definately so much easier now with the extra section! :-)

Update Galician Translations 2023-04-23

---

src/lang/extra/korean.txt

Update: Korean translation up to e26bea6

---

src/lang/extra/galician.txt

Hey There! Updating the galician translations! Also thanks again for the help with the sound issue :-)

🌐 Update Galician Translations up to 0.53.3

---

src/lang/extra/korean.txt

Update: Korean translation for 0.53.3

---

src/lang/extra/korean.txt

Merge this just before new release.
Please let me know if additional extra string is added

Update: Korean translation up to 5615cee

---

README.md

A minor typo in the `README.md`'s lead section.
Fixed the typo.
None. …

Fix a minor typo in the README.md

---

src/lang/extra/korean.txt

Tell me there's any problem :)

Update: Korean translation up to 7ffc9c9

---

src/lang/extra/czech.txt

Tried to update the Czech translation. I am sorry for my bad git skills, I just love my language and I'm not a Linux user, I hope this will work. Please be merciful ':)

Update: Czech translation up to 0.54.4.

---

src/lang/extra/korean.txt

Update: Korean translation up to d7ef141

---

src/lang/extra/galician.txt

Hey there! Updating translations one more time :-)

🌐 Update Galician Translations up to 0.54.4

---

src/lang/extra/galician.txt

September comes, and so do the updates! :-)

🌐 Update Galician Translations up to 0.55.1

---

src/lang/extra/simplified_chinese.txt

Fixed Simplified Chinese translation

---

src/lang/extra/korean.txt

Update: Korean translation up to 3da9f52

---

src/lang/extra/galician.txt

Hey there! Just checking out the latest translations!

🌐 Update Galician Translations up to 2023-11-18

---

src/lang/extra/korean.txt

Merge this before new release :)

Update: Korean translation up to 592c038

---

src/lang/extra/korean.txt

Update: Korean translation up to 0.57.0

---

src/lang/extra/korean.txt

https://github.com/JGRennison/OpenTTD-patches/pull/642#issuecomment-1925305705
It was my mistake, oops

Update: Missing Korean translation

---

src/lang/extra/galician.txt

Hey there, just checking in for the 14.0 release! :-)

🌐 Update Galician Translations 2024-04-14

---

src/lang/extra/galician.txt

Hello there!
Monthly update to the translations here!

🌐 Update Galician Translations 2024-05-26

---

src/lang/extra/simplified_chinese.txt

See OpenTTD PR #12717.\n Note: this PR only contains improvements to the current language file, and does not contain translations of any new strings.

Fix: punctuations in zh_CN

---

src/lang/extra/galician.txt

🌐 Update galician Translations 2024-06-28

---

src/lang/extra/russian.txt

What is the minimum number of towns needed to generate public roads? They are didn't appear if create map only with 2 towns.

Update: Russian translation up to v0.60.1

---

src/lang/extra/galician.txt

🌐 Galician Translations up to July 28th

---

src/lang/extra/korean.txt

Some fixes for the translation.

Fix: Korean translation

---

src/lang/extra/simplified_chinese.txt

Fixed many errors, and rephrased many strings.

Update: Simplified Chinese translations

---

src/lang/extra/korean.txt

Update: Korean translation up to 0.61.0

---

src/lang/extra/galician.txt

Updating translations for the latest release!

🌐 Galician translations 2024-08-24

---

src/lang/extra/simplified_chinese.txt

Update translations
* ai_changelog.hpp, game_changelog.hpp need updating.
* [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

Update: Simplified Chinese translation

---

src/lang/extra/galician.txt

Hey there! Monthly update here :-)

Galician translations

---

src/lang/extra/galician.txt

Hey there, updating for the next patch!

🌐 Update galician translations

---

src/lang/extra/traditional_chinese.txt

This is a significant update for Traditional Chinese. 
There might be some issues, 
but we need to test how it works and then address them. 
;-)

Update: Traditional Chinese Translation

---

src/lang/extra/galician.txt

🌐 feat: galician translations 2024-11-24

---

src/lang/extra/traditional_chinese.txt

Update the translation to correct the vocabulary and translate the new item.
; -)

Update: Traditional Chinese Translation 

---

src/lang/extra/galician.txt

Last check-in of the year, Happy 2025! :-)

🌐 Galician Localization December 2024

---

src/lang/extra/galician.txt

Hey there! Monthly update here :-)

🌐 Galician Localization January 2025

---

src/lang/extra/korean.txt

Update: Korean translation based on 250206

---

src/lang/extra/galician.txt

🌐 Galician Localization February 2025

---

src/lang/extra/galician.txt

🌐 Galician Localization March 2025

---

src/lang/extra/traditional_chinese.txt

Update & Fix Traditional Chinese Translation

Update: Traditional Chinese Translation 2025.03.31 

---

src/lang/extra/korean.txt

Update: Korean translation up to 0.65.0

---

src/lang/extra/korean.txt

Update: Korean translation up to c3b8f7bc

---

src/lang/extra/traditional_chinese.txt

Update TC Translation for these:
STR_WAYPOINT_VIEW_RENAME_TOOLTIP_EXTRA
STR_ERROR_WAYPOINTS_NOT_IN_SAME_TOWN
STR_ERROR_WAYPOINTS_NOT_COMPATIBLE
STR_ERROR_CAN_T_EXCHANGE_WAYPOINT_NAMES

Update traditional chinese Translation 20250419

---

src/lang/extra/galician.txt

🌐 Galician Localization April 2025

---

src/lang/extra/traditional_chinese.txt

Update TC Translation for these:
STR_NEWGRF_SETTINGS_UPGRADE_TOOLTIP_EXTRA
STR_NEWGRF_SETTINGS_MOVEUP_TOOLTIP_EXTRA
STR_NEWGRF_SETTINGS_MOVEDOWN_TOOLTIP_EXTRA
STR_SCHDISPATCH_ADJUST_TOOLTIP_SELECTED
STR_SCHDISPATCH_ADJUST_CAPTION_SLOT_PREFIXED
STR_ERROR_SCHDISPATCH_SLOT_ALREADY_EXISTS_AT_ADJUSTED_TIME

Update: Traditional Chinese Translation 2025.04.26 

---

src/lang/extra/traditional_chinese.txt

Fix Traditional Chinese Translation

Update: Fix Traditional Chinese Translation 2025.04.28

---

src/lang/extra/galician.txt

🌐 Galician Localization May 2025

---

src/vehicle_gui.cpp

The vehicle list can display the cargoes for vehicles. However when grouping by Shared Orders, this goes away.
Allow the vehicle list to display cargoes for groups of vehicles grouped by Shared Orders by aggregating all cargoes of the vehicles in the group and displaying that.
The code for displaying these things is pretty copy paste / nested, so I am sure I am missing other grouping possibilities. Personally I use the group by shared orders a lot and wanted to see the cargoes.
* This …

vehicle list: Show cargoes when grouping by shared orders

---

src/lang/extra/korean.txt

Update: Korean translation up to 7bccdb73

---

src/lang/extra/galician.txt

Hello there! Updating some for the summer! :-)

🌐 Galician Localization July 2025

---

src/order_serialisation.cpp

Adds export for jump taken travel time
Renames "condition" tag to "condition-variable"

Change: Conditional order serialization improvments

---

src/order_serialisation.cpp
src/schdispatch.h
src/schdispatch_cmd.cpp
src/schdispatch_gui.cpp

Also fixes import of renamed order tags

Order list serialization fixes

---

src/lang/english.txt
src/settingentry_gui.cpp
src/settings_type.h
src/station_cmd.cpp
src/table/settings/game_settings.ini

When focusing on regular-interval timetables, service can be low sometimes and waiting cargo will disappear before the sceduled vehicle arrives.
This feature adds the option in the settings to disable the automatic cargo truncation.
It does not affect the station rating. It does not prevent the calculation for the truncation, as it is partially used for the station rating.
* ai_changelog.hpp, game_changelog.hpp need …

Feature: Add an option to disable automatic truncation of cargo

---

src/lang/extra/galician.txt

🌐 Galician Localization September 2025
